### ISSUE TITLE
Unknown source of "self_defined" package

### ISSUE THREAD

**Issue by tasos-alex** [drwangxian/dilated_conv_model_for_melody_extraction#1]
I want to run training_and_inference.py, but there is this "self_defined" package that is unknown and gives an error. It occurs on line 26 from general/shaun/shaun.py and line 2 from general/shaun/acoustic_model_shaun.py. Is this some local folder you created on your machine? I can't seem to figure out what it is. Thanks in advance.

**Comment by drwangxian** [comment]
sorry for forgetting to upload self_defined. If you have any further problems, please advise me. Thanks!

**Comment by tasos-alex** [comment]
That is great, thank you very much!
